apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: quasselstrippe-data-pvc
  namespace: quasselstrippe
  labels:
    app.kubernetes.io/name: quasselstrippe-backend
    app.kubernetes.io/component: database
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
